### ISSUE TITLE
测试用户list接口返回服务器正忙

### ISSUE THREAD

**Issue by logtous** [didi/AgileTC#147]
![image](https://user-images.githubusercontent.com/88697234/162662783-c9d24b5e-10f7-4d3b-8e9f-0cdf1693d275.png)
其他用例都正常，就这一个报整个错误

日志
```
3|AgileTC  | [11:50:19:744] [ERROR] - com.xiaoju.framework.entity.exception.ExpHandler.handlerException(ExpHandler.java:70) - SERVER_BUSY_ERROR
3|AgileTC  | java.lang.NullPointerException
3|AgileTC  |    at com.xiaoju.framework.util.TreeUtil.getCaseNum(TreeUtil.java:253)
3|AgileTC  |    at com.xiaoju.framework.util.TreeUtil.getCaseNum(TreeUtil.java:255)
3|AgileTC  |    at com.xiaoju.framework.util.TreeUtil.getCaseNum(TreeUtil.java:255)
3|AgileTC  |    at com.xiaoju.framework.util.TreeUtil.getCaseNum(TreeUtil.java:255)
3|AgileTC  |    at com.xiaoju.framework.util.TreeUtil.getCaseNum(TreeUtil.java:255)
3|AgileTC  |    at com.xiaoju.framework.service.impl.CaseServiceImpl.getCountByCondition(CaseServiceImpl.java:211)
3|AgileTC  |    at com.xiaoju.framework.service.impl.CaseServiceImpl$$FastClassBySpringCGLIB$$3a068117.invoke(<generated>)
3|AgileTC  |    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
3|AgileTC  |    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
3|AgileTC  |    at com.xiaoju.framework.service.impl.CaseServiceImpl$$EnhancerBySpringCGLIB$$f8b8ecd2.getCountByCondition(<generated>)
3|AgileTC  |    at com.xiaoju.framework.controller.CaseController.getCountByCondition(CaseController.java:169)
3|AgileTC  |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
3|AgileTC  |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
3|AgileTC  |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
3|AgileTC  |    at java.lang.reflect.Method.invoke(Method.java:498)
3|AgileTC  |    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
3|AgileTC  |    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
3|AgileTC  |    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
3|AgileTC  |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
3|AgileTC  |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
3|AgileTC  |    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
3|AgileTC  |    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
3|AgileTC  |    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
3|AgileTC  |    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
3|AgileTC  |    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
3|AgileTC  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
3|AgileTC  |    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
3|AgileTC  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
3|AgileTC  |    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
3|AgileTC  |    at com.xiaoju.framework.filter.WebSocketFilter$WsAuthFilter.doFilter(WebSocketFilter.java:52)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
3|AgileTC  |    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
3|AgileTC  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
3|AgileTC  |    at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
3|AgileTC  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
3|AgileTC  |    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
3|AgileTC  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
3|AgileTC  |    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
3|AgileTC  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
3|AgileTC  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
3|AgileTC  |    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
3|AgileTC  |    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
3|AgileTC  |    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
3|AgileTC  |    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
3|AgileTC  |    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
3|AgileTC  |    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
3|AgileTC  |    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
3|AgileTC  |    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
3|AgileTC  |    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
3|AgileTC  |    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
3|AgileTC  |    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
3|AgileTC  |    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
3|AgileTC  |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
3|AgileTC  |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
3|AgileTC  |    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
3|AgileTC  |    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Master-An** [comment]
我也遇到了，同求指点
